name: Chris Geissler
markdown: kramdown
theme: jekyll-theme-midnight


layout: page
title: "Research"
permalink: /research/

layout: page
title: "Teaching"
permalink: /research/

layout: page
title: "Publications"
permalink: /publications/

layout: page
title: "Chris Geissler"
description: Phonetics, phonology, and teaching