name: Christopher Geissler
markdown: kramdown
theme: jekyll-theme-midnight

layout: page
title: "Research"
permalink: /research/

layout: page
title: "Teaching"
permalink: /research/

layout: page
title: "Publications"
permalink: /publications/

layout: page
title: "Resources"
permalink: /resources/

layout: page
title: "Christopher Geissler"
description: Phonetics, Phonology, Teaching
